"""fix add accounts monero

Revision ID: d1b0af894f74
Revises: 1eb00ae6e4d7
Create Date: 2024-11-03 09:35:28.333335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b0af894f74'
down_revision: Union[str, None] = '1eb00ae6e4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monero_address', 'address',
               existing_type=sa.VARCHAR(length=95),
               nullable=False)
    op.alter_column('monero_address', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('monero_address', 'sub_address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('monero_deposit_transaction', 'address_in',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=95),
               existing_nullable=False)
    op.alter_column('monero_withdraw_transaction', 'address_out',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=95),
               existing_nullable=False)
    op.alter_column('users', 'monero_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'monero_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('monero_withdraw_transaction', 'address_out',
               existing_type=sa.String(length=95),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('monero_deposit_transaction', 'address_in',
               existing_type=sa.String(length=95),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('monero_address', 'sub_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('monero_address', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('monero_address', 'address',
               existing_type=sa.VARCHAR(length=95),
               nullable=True)
    # ### end Alembic commands ###
