"""fix add fee monero

Revision ID: 11f997b987b1
Revises: 65bd411ae4fa
Create Date: 2024-11-07 04:32:46.175297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f997b987b1'
down_revision: Union[str, None] = '65bd411ae4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monero_withdraw_transaction', sa.Column('service_transfer_fee', sa.Float(), nullable=False))
    op.add_column('monero_withdraw_transaction', sa.Column('network_transfer_fee', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monero_withdraw_transaction', 'network_transfer_fee')
    op.drop_column('monero_withdraw_transaction', 'service_transfer_fee')
    # ### end Alembic commands ###
