"""fix add monero heigt

Revision ID: 8b9ebe2c2a3f
Revises: 1a8774ccee69
Create Date: 2024-11-01 02:16:02.649725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9ebe2c2a3f'
down_revision: Union[str, None] = '1a8774ccee69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'monero_address', ['id'])
    op.add_column('monero_deposit_transaction', sa.Column('height', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'monero_deposit_transaction', ['id'])
    op.create_unique_constraint(None, 'monero_withdraw_transaction', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monero_withdraw_transaction', type_='unique')
    op.drop_constraint(None, 'monero_deposit_transaction', type_='unique')
    op.drop_column('monero_deposit_transaction', 'height')
    op.drop_constraint(None, 'monero_address', type_='unique')
    # ### end Alembic commands ###
