"""fix add accounts monero

Revision ID: 2dd40202a8ba
Revises: d1b0af894f74
Create Date: 2024-11-03 09:55:12.763072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd40202a8ba'
down_revision: Union[str, None] = 'd1b0af894f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('monero_address_account_id_key', 'monero_address', type_='unique')
    op.drop_constraint('monero_deposit_transaction_account_id_key', 'monero_deposit_transaction', type_='unique')
    op.drop_constraint('monero_withdraw_transaction_account_id_key', 'monero_withdraw_transaction', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('monero_withdraw_transaction_account_id_key', 'monero_withdraw_transaction', ['account_id'])
    op.create_unique_constraint('monero_deposit_transaction_account_id_key', 'monero_deposit_transaction', ['account_id'])
    op.create_unique_constraint('monero_address_account_id_key', 'monero_address', ['account_id'])
    # ### end Alembic commands ###
