"""add monero db

Revision ID: 1a8774ccee69
Revises: be696d8ad24b
Create Date: 2024-10-31 22:39:34.643641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8774ccee69'
down_revision: Union[str, None] = 'be696d8ad24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monero_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('monero_deposit_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_id', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('address_in', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('monero_withdraw_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_id', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('address_out', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('users', sa.Column('monero_balance', sa.BigInteger(), nullable=False))
    op.drop_column('users', 'monero')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('monero', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'monero_balance')
    op.drop_table('monero_withdraw_transaction')
    op.drop_table('monero_deposit_transaction')
    op.drop_table('monero_address')
    # ### end Alembic commands ###
