"""fix monero tx_id to tx_hash

Revision ID: a055e020c759
Revises: 8b9ebe2c2a3f
Create Date: 2024-11-01 02:36:13.852479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a055e020c759'
down_revision: Union[str, None] = '8b9ebe2c2a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monero_deposit_transaction', sa.Column('tx_hash', sa.String(length=300), nullable=False))
    op.drop_column('monero_deposit_transaction', 'tx_id')
    op.add_column('monero_withdraw_transaction', sa.Column('tx_hash', sa.String(length=300), nullable=False))
    op.drop_column('monero_withdraw_transaction', 'tx_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monero_withdraw_transaction', sa.Column('tx_id', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_column('monero_withdraw_transaction', 'tx_hash')
    op.add_column('monero_deposit_transaction', sa.Column('tx_id', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_column('monero_deposit_transaction', 'tx_hash')
    # ### end Alembic commands ###
