"""fix amount coin type bigint to float

Revision ID: 1fcdcacb1299
Revises: a055e020c759
Create Date: 2024-11-01 03:18:57.753465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fcdcacb1299'
down_revision: Union[str, None] = 'a055e020c759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monero_deposit_transaction', 'amount',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('monero_withdraw_transaction', 'amount',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('users', 'monero_balance',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'monero_balance',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('monero_withdraw_transaction', 'amount',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('monero_deposit_transaction', 'amount',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
